[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[dev]
  command = "vite"
  targetPort = 5173
  port = 8888
  publish = "dist"


[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Optional: Configure redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
