[build]
  base = "project"
  publish = "dist"
  command = "npm run build"

[dev]
  command = "npm run dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dependencies]
  helmet = "^7.1.0"
  jsonwebtoken = "^9.0.2"
  lucide-react = "^0.344.0"
  mongoose = "^8.15.0"
  morgan = "^1.10.0"
  nodemailer = "^6.9.9"
  otp-generator = "^4.0.1"
  react = "^18.3.1"
  react-chartjs-2 = "^5.2.0"
  react-dom = "^18.3.1"
  react-router-dom = "^6.22.1"
  react-toastify = "^10.0.4"
  yup = "^1.3.3"
  zustand = "^4.5.0"

[devDependencies]
  @eslint/js = "^9.9.1"
  @types/node = "^20.11.19"
