[build]
  # No base directory needed - code is in root
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Optional: Configure redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
